# Generated by Django 5.0.1 on 2024-02-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=10)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
        ),
    ]
